# Single source of truth for every PCoin icon.
#
# Emits, from one set of constants:
#   * Android VectorDrawable XML  (per flavour: adaptive foreground + legacy)
#   * SVG                          (website favicon and logo)
#   * PNG                          (every launcher size + the 512 Play needs)
#   * ICO                          (Windows tray and installer, via the PNGs)
#
# Everything is generated by the SAME helper functions that build the
# GraphicsPath used for rasterising, so the shipped vector and the shipped
# bitmap cannot drift apart. That mattered: hand-keeping two implementations in
# step is exactly how an icon ends up subtly different on one platform.
#
# Canvas is Android's adaptive 108x108. A launcher shows the middle 72x72; the
# central 66x66 circle is the only region guaranteed to survive every OEM mask.

Add-Type -AssemblyName System.Drawing

$ErrorActionPreference = 'Stop'

# Paths derive from this script's own location, so the generator runs from
# any clone. Nothing here may point at a machine-specific directory.
$HERE    = Split-Path -Parent $MyInvocation.MyCommand.Path
$REPO    = Split-Path -Parent (Split-Path -Parent $HERE)
$SCRATCH = $HERE
$ANDROID = Join-Path $REPO 'contrib\android\app\src'
$OUT     = Join-Path $HERE 'out'
if (-not (Test-Path $OUT)) { New-Item -ItemType Directory -Force $OUT | Out-Null }

# --- constants ---------------------------------------------------------------
$GRAPHITE = '#262B33'
$CXC      = 54.0

# coin, at scale 1
$RING_MID = 27.5     # centre of the milled band
$RING_W   = 6.5      # its thickness
$TEETH    = 16
$FACE_R   = 21.0
$STAR_O   = 15.5
$STAR_I   = 5.5

# wallet layout
$W_SCALE  = 0.70
$W_CY     = 42.5     # coin centre; keeps the milled edge inside the 66dp circle
$BASE_TOP = 64.0

function Deg2Rad([double]$d) { return $d * [Math]::PI / 180.0 }

# --- geometry: each helper returns BOTH a GraphicsPath and SVG path data ------

function New-TeethGeometry([double]$cy, [double]$scale) {
    $rIn  = ($RING_MID - $RING_W / 2.0) * $scale
    $rOut = ($RING_MID + $RING_W / 2.0) * $scale
    $step = 360.0 / $TEETH
    $arc  = $step / 2.0                       # tooth on, gap off

    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $sb = New-Object System.Text.StringBuilder

    for ($i = 0; $i -lt $TEETH; $i++) {
        $a0 = -90.0 + $i * $step
        $a1 = $a0 + $arc

        # Scalars, deliberately. PowerShell's comma binds tighter than * , so
        # @($a + $b * f(x), $c) multiplies $b by the ARRAY (f(x), $c) and fails
        # with a op_Multiply error that points at the wrong thing entirely.
        $r0 = Deg2Rad $a0
        $r1 = Deg2Rad $a1
        $p0x = $CXC + $rOut * [Math]::Cos($r0); $p0y = $cy + $rOut * [Math]::Sin($r0)
        $p1x = $CXC + $rOut * [Math]::Cos($r1); $p1y = $cy + $rOut * [Math]::Sin($r1)
        $p2x = $CXC + $rIn  * [Math]::Cos($r1); $p2y = $cy + $rIn  * [Math]::Sin($r1)
        $p3x = $CXC + $rIn  * [Math]::Cos($r0); $p3y = $cy + $rIn  * [Math]::Sin($r0)

        $path.StartFigure()
        $path.AddArc([single]($CXC - $rOut), [single]($cy - $rOut),
                     [single]($rOut * 2), [single]($rOut * 2), [single]$a0, [single]$arc)
        $path.AddLine([single]$p1x, [single]$p1y, [single]$p2x, [single]$p2y)
        $path.AddArc([single]($CXC - $rIn), [single]($cy - $rIn),
                     [single]($rIn * 2), [single]($rIn * 2), [single]$a1, [single](-$arc))
        $path.CloseFigure()

        [void]$sb.Append(('M{0:0.##},{1:0.##}' -f $p0x, $p0y))
        [void]$sb.Append(('A{0:0.##},{0:0.##} 0 0 1 {1:0.##},{2:0.##}' -f $rOut, $p1x, $p1y))
        [void]$sb.Append(('L{0:0.##},{1:0.##}' -f $p2x, $p2y))
        [void]$sb.Append(('A{0:0.##},{0:0.##} 0 0 0 {1:0.##},{2:0.##}' -f $rIn, $p3x, $p3y))
        [void]$sb.Append('Z')
    }
    return @{ Path = $path; Data = $sb.ToString() }
}

function New-FaceGeometry([double]$cy, [double]$scale) {
    # Disc with the star cut out of it: one path, evenOdd. Cutting rather than
    # overpainting means the foreground is genuinely transparent there, so the
    # Android 13 monochrome layer and any background both composite correctly.
    $r = $FACE_R * $scale
    $so = $STAR_O * $scale
    $si = $STAR_I * $scale

    $path = New-Object System.Drawing.Drawing2D.GraphicsPath -ArgumentList ([System.Drawing.Drawing2D.FillMode]::Alternate)
    $path.AddEllipse([single]($CXC - $r), [single]($cy - $r), [single]($r * 2), [single]($r * 2))

    $pts = New-Object System.Collections.ArrayList
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append(('M{0:0.##},{1:0.##}' -f ($CXC + $r), $cy))
    [void]$sb.Append(('A{0:0.##},{0:0.##} 0 1 1 {1:0.##},{2:0.##}' -f $r, ($CXC - $r), $cy))
    [void]$sb.Append(('A{0:0.##},{0:0.##} 0 1 1 {1:0.##},{2:0.##}Z' -f $r, ($CXC + $r), $cy))

    for ($i = 0; $i -lt 8; $i++) {
        $rad = if ($i % 2 -eq 0) { $so } else { $si }
        $a = Deg2Rad (-90.0 + $i * 45.0)
        $x = $CXC + $rad * [Math]::Cos($a)
        $y = $cy + $rad * [Math]::Sin($a)
        [void]$pts.Add((New-Object System.Drawing.PointF([single]$x, [single]$y)))
        [void]$sb.Append(('{0}{1:0.##},{2:0.##}' -f $(if ($i -eq 0) { 'M' } else { 'L' }), $x, $y))
    }
    [void]$sb.Append('Z')
    $path.AddPolygon([System.Drawing.PointF[]]$pts.ToArray())

    return @{ Path = $path; Data = $sb.ToString() }
}

function New-WordGeometry {
    # The base plate with WALLET knocked out of it, again as one evenOdd path.
    # Winding rule detail that matters: the counter inside the A sits at three
    # crossings, so it fills back to white -- which is what a real counter does.
    $wordData = Get-Content (Join-Path $SCRATCH 'wallet-word.path') -Raw

    $path = New-Object System.Drawing.Drawing2D.GraphicsPath -ArgumentList ([System.Drawing.Drawing2D.FillMode]::Alternate)
    $path.AddRectangle((New-Object System.Drawing.RectangleF(0, [single]$BASE_TOP, 108, [single](108 - $BASE_TOP))))

    # rebuild the identical word path from the same font call
    $ff = New-Object System.Drawing.FontFamily('Segoe UI')
    $style = [int][System.Drawing.FontStyle]::Bold
    $fmt = [System.Drawing.StringFormat]::GenericTypographic
    $text = 'WALLET'; $em = 11.0; $track = 1.1
    $widths = @(); $total = 0.0
    foreach ($ch in $text.ToCharArray()) {
        $p = New-Object System.Drawing.Drawing2D.GraphicsPath
        $p.AddString([string]$ch, $ff, $style, [single]$em, (New-Object System.Drawing.PointF(0, 0)), $fmt)
        $b = $p.GetBounds(); $w = [double]$b.Width
        if ($w -le 0) { $w = $em * 0.5 }
        $widths += $w; $total += $w + $track; $p.Dispose()
    }
    $total -= $track
    $x = $CXC - $total / 2.0
    for ($i = 0; $i -lt $text.Length; $i++) {
        $p = New-Object System.Drawing.Drawing2D.GraphicsPath
        $p.AddString([string]$text[$i], $ff, $style, [single]$em, (New-Object System.Drawing.PointF(0, 0)), $fmt)
        $b = $p.GetBounds()
        $m = New-Object System.Drawing.Drawing2D.Matrix
        $m.Translate([single]($x - $b.X), [single](73.0 - $b.Y - $b.Height / 2.0))
        $p.Transform($m); $path.AddPath($p, $false)
        $m.Dispose(); $p.Dispose()
        $x += $widths[$i] + $track
    }
    $ff.Dispose()

    $data = ('M0,{0}L108,{0}L108,108L0,108Z' -f $BASE_TOP) + $wordData
    return @{ Path = $path; Data = $data }
}

# --- rasteriser --------------------------------------------------------------
function Render-Icon {
    param([string]$Flavour, [int]$Size, [string]$Path, [string]$Shape = 'squircle')

    $bmp = New-Object System.Drawing.Bitmap($Size, $Size,
        [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode      = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
    $g.Clear([System.Drawing.Color]::Transparent)

    if ($Shape -ne 'square') {
        $clip = New-Object System.Drawing.Drawing2D.GraphicsPath
        if ($Shape -eq 'round') {
            $clip.AddEllipse(0, 0, $Size, $Size)
        } else {
            $r = [double]$Size * 0.28; $d = $r * 2.0
            $clip.AddArc(0.0, 0.0, $d, $d, 180.0, 90.0)
            $clip.AddArc($Size - $d, 0.0, $d, $d, 270.0, 90.0)
            $clip.AddArc($Size - $d, $Size - $d, $d, $d, 0.0, 90.0)
            $clip.AddArc(0.0, $Size - $d, $d, $d, 90.0, 90.0)
            $clip.CloseFigure()
        }
        $g.SetClip($clip); $clip.Dispose()
    }

    $s = [double]$Size / 72.0
    $g.ScaleTransform([single]$s, [single]$s)
    $g.TranslateTransform(-18.0, -18.0)

    $fb = New-Object System.Drawing.SolidBrush([System.Drawing.ColorTranslator]::FromHtml($GRAPHITE))
    $wb = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
    $g.FillRectangle($fb, 0, 0, 108, 108)

    if ($Flavour -eq 'miner') {
        $t = New-TeethGeometry 54.0 1.0;      $g.FillPath($wb, $t.Path); $t.Path.Dispose()
        $f = New-FaceGeometry  54.0 1.0;      $g.FillPath($wb, $f.Path); $f.Path.Dispose()
    } else {
        $t = New-TeethGeometry $W_CY $W_SCALE; $g.FillPath($wb, $t.Path); $t.Path.Dispose()
        $f = New-FaceGeometry  $W_CY $W_SCALE; $g.FillPath($wb, $f.Path); $f.Path.Dispose()
        $w = New-WordGeometry;                 $g.FillPath($wb, $w.Path); $w.Path.Dispose()
    }

    $fb.Dispose(); $wb.Dispose(); $g.Dispose()
    $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
}

# --- emit Android VectorDrawable --------------------------------------------
function Write-AndroidForeground([string]$Flavour, [string]$File) {
    if ($Flavour -eq 'miner') {
        $t = New-TeethGeometry 54.0 1.0
        $f = New-FaceGeometry  54.0 1.0
        $paths = @(
            @{ d = $t.Data; rule = 'nonZero'; c = '  <!-- milled edge: 16 struck teeth -->' },
            @{ d = $f.Data; rule = 'evenOdd'; c = '  <!-- face, with the star cut out of it -->' }
        )
    } else {
        $t = New-TeethGeometry $W_CY $W_SCALE
        $f = New-FaceGeometry  $W_CY $W_SCALE
        $w = New-WordGeometry
        $paths = @(
            @{ d = $t.Data; rule = 'nonZero'; c = '  <!-- milled edge, 70% -->' },
            @{ d = $f.Data; rule = 'evenOdd'; c = '  <!-- face, star cut out -->' },
            @{ d = $w.Data; rule = 'evenOdd'; c = '  <!-- base plate, WALLET knocked out as outlines -->' }
        )
    }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<!--')
    [void]$sb.AppendLine('  PCoin ' + $Flavour + ' launcher foreground: a struck coin.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('  GENERATED. Do not hand-edit. Regenerate from scratchpad/make_icons.ps1,')
    [void]$sb.AppendLine('  which emits this file, the SVG the website uses, every PNG and the Windows')
    [void]$sb.AppendLine('  .ico from one set of constants. Editing here silently desyncs the platforms.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('  108x108 is the adaptive viewport; a launcher shows only the middle 72x72 and')
    [void]$sb.AppendLine('  only the central 66x66 circle survives every OEM mask, so the whole mark sits')
    [void]$sb.AppendLine('  inside that circle.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('  The shapes are CUT, not overpainted: the star is a hole in the face and the')
    [void]$sb.AppendLine('  lettering is a hole in the base, both via evenOdd. That keeps the foreground')
    [void]$sb.AppendLine('  genuinely transparent there, which is what makes the Android 13 monochrome')
    [void]$sb.AppendLine('  layer render as a coin rather than a solid blob.')
    if ($Flavour -eq 'wallet') {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('  VectorDrawable has no <text>, so WALLET ships as outlines. Changing the word')
        [void]$sb.AppendLine('  means regenerating, not editing a string.')
    }
    [void]$sb.AppendLine('-->')
    [void]$sb.AppendLine('<vector xmlns:android="http://schemas.android.com/apk/res/android"')
    [void]$sb.AppendLine('    android:width="108dp"')
    [void]$sb.AppendLine('    android:height="108dp"')
    [void]$sb.AppendLine('    android:viewportWidth="108"')
    [void]$sb.AppendLine('    android:viewportHeight="108">')
    foreach ($p in $paths) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine($p.c)
        [void]$sb.AppendLine('    <path')
        [void]$sb.AppendLine('        android:fillColor="#FFFFFF"')
        [void]$sb.AppendLine('        android:fillType="' + $p.rule + '"')
        [void]$sb.AppendLine('        android:pathData="' + $p.d + '" />')
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('</vector>')

    $dir = Split-Path $File -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
    Set-Content -Path $File -Value $sb.ToString() -Encoding utf8
    Write-Output ("  {0,-62} {1,6:N0} B" -f $File.Replace($REPO + '\', ''), (Get-Item $File).Length)
}

function Write-AndroidLegacy([string]$Flavour, [string]$File) {
    # API 24-25 predate adaptive icons and have no mask, so this draws its own
    # rounded background. minSdk is 24, so it is not optional.
    if ($Flavour -eq 'miner') {
        $t = New-TeethGeometry 54.0 1.0; $f = New-FaceGeometry 54.0 1.0
        $paths = @(@{ d = $t.Data; rule = 'nonZero' }, @{ d = $f.Data; rule = 'evenOdd' })
    } else {
        $t = New-TeethGeometry $W_CY $W_SCALE; $f = New-FaceGeometry $W_CY $W_SCALE; $w = New-WordGeometry
        $paths = @(@{ d = $t.Data; rule = 'nonZero' }, @{ d = $f.Data; rule = 'evenOdd' }, @{ d = $w.Data; rule = 'evenOdd' })
    }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<!--')
    [void]$sb.AppendLine('  Legacy launcher icon for API 24-25, which predate adaptive icons.')
    [void]$sb.AppendLine('  GENERATED by scratchpad/make_icons.ps1. Do not hand-edit.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('  Same geometry as the adaptive foreground, on its own rounded background')
    [void]$sb.AppendLine('  because there is no mask to supply one. Without this file')
    [void]$sb.AppendLine('  @mipmap/ic_launcher fails to resolve on those two API levels and the app')
    [void]$sb.AppendLine('  will not install.')
    [void]$sb.AppendLine('-->')
    [void]$sb.AppendLine('<vector xmlns:android="http://schemas.android.com/apk/res/android"')
    [void]$sb.AppendLine('    android:width="108dp"')
    [void]$sb.AppendLine('    android:height="108dp"')
    [void]$sb.AppendLine('    android:viewportWidth="108"')
    [void]$sb.AppendLine('    android:viewportHeight="108">')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('    <path')
    [void]$sb.AppendLine('        android:fillColor="@color/ic_launcher_background"')
    [void]$sb.AppendLine('        android:pathData="M20,4 h68 a16,16 0 0 1 16,16 v68 a16,16 0 0 1 -16,16 h-68 a16,16 0 0 1 -16,-16 v-68 a16,16 0 0 1 16,-16 z" />')
    foreach ($p in $paths) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    <path')
        [void]$sb.AppendLine('        android:fillColor="#FFFFFF"')
        [void]$sb.AppendLine('        android:fillType="' + $p.rule + '"')
        [void]$sb.AppendLine('        android:pathData="' + $p.d + '" />')
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('</vector>')

    $dir = Split-Path $File -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
    Set-Content -Path $File -Value $sb.ToString() -Encoding utf8
    Write-Output ("  {0,-62} {1,6:N0} B" -f $File.Replace($REPO + '\', ''), (Get-Item $File).Length)
}

function Write-Svg([string]$Flavour, [string]$File) {
    if ($Flavour -eq 'miner') {
        $t = New-TeethGeometry 54.0 1.0; $f = New-FaceGeometry 54.0 1.0
        $body = '  <path fill="#FFF" d="' + $t.Data + '"/>' + "`n" +
                '  <path fill="#FFF" fill-rule="evenodd" d="' + $f.Data + '"/>'
    } else {
        $t = New-TeethGeometry $W_CY $W_SCALE; $f = New-FaceGeometry $W_CY $W_SCALE; $w = New-WordGeometry
        $body = '  <path fill="#FFF" d="' + $t.Data + '"/>' + "`n" +
                '  <path fill="#FFF" fill-rule="evenodd" d="' + $f.Data + '"/>' + "`n" +
                '  <path fill="#FFF" fill-rule="evenodd" d="' + $w.Data + '"/>'
    }
    $svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" height="512">' + "`n" +
           '  <rect x="18" y="18" width="72" height="72" fill="' + $GRAPHITE + '"/>' + "`n" +
           $body + "`n</svg>`n"
    Set-Content -Path $File -Value $svg -Encoding utf8
    Write-Output ("  {0,-62} {1,6:N0} B" -f (Split-Path $File -Leaf), (Get-Item $File).Length)
}

# --- run ---------------------------------------------------------------------
Write-Output 'Android vector drawables:'
Write-AndroidForeground 'miner'  (Join-Path $ANDROID 'miner\res\drawable\ic_launcher_foreground.xml')
Write-AndroidForeground 'wallet' (Join-Path $ANDROID 'wallet\res\drawable\ic_launcher_foreground.xml')
Write-AndroidLegacy     'miner'  (Join-Path $ANDROID 'miner\res\mipmap\ic_launcher.xml')
Write-AndroidLegacy     'wallet' (Join-Path $ANDROID 'wallet\res\mipmap\ic_launcher.xml')

Write-Output ''
Write-Output 'SVG:'
Write-Svg 'miner'  (Join-Path $OUT 'pcoin-miner.svg')
Write-Svg 'wallet' (Join-Path $OUT 'pcoin-wallet.svg')

Write-Output ''
Write-Output 'PNG:'
foreach ($fl in 'miner', 'wallet') {
    foreach ($sz in 512, 256, 192, 128, 96, 64, 48, 32, 16) {
        $p = Join-Path $OUT ("pcoin-$fl-$sz.png")
        Render-Icon -Flavour $fl -Size $sz -Path $p
    }
    Render-Icon -Flavour $fl -Size 512 -Path (Join-Path $OUT "pcoin-$fl-512-square.png") -Shape 'square'
    Render-Icon -Flavour $fl -Size 512 -Path (Join-Path $OUT "pcoin-$fl-512-round.png")  -Shape 'round'
    Write-Output ("  $fl : 7 launcher sizes + square (Play) + round")
}

Write-Output ''
Write-Output ("done -> " + $OUT)
