package org.pcoin.miner

import android.content.Context
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import org.pcoin.miner.wallet.Redact
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit
import kotlin.concurrent.thread

/**
 * Owns the bitcoind child process and everything said to it over RPC.
 *
 * Lifecycle, in order:
 *   1. [writeConf]      - regenerate pcoin.conf in the datadir
 *   2. [probe]          - is a node already up? (START_STICKY restart, or a
 *                         foreign node squatting on the RPC port)
 *   3. [spawn]          - exec libbitcoind.so from nativeLibraryDir
 *   4. [awaitRpc]       - wait out the RPC warmup
 *   5. [loadKnownWallets] - load the wallets this install owns; create NONE
 *   6. [payoutAddress]  - read the persisted payout address; never invent one
 *   7. [startMining] / [stopMining] / [minerInfo] / [stats]
 *   8. [shutdown]       - stopmining, stop, wait, then force
 *
 * Wallet CREATION deliberately does not appear in that list. It happens once,
 * in the foreground, in the setup or restore flow, where the recovery phrase is
 * in hand and the node's answer can be cross-checked against a locally derived
 * address. Nothing here creates a wallet as a side effect of starting up.
 *
 * Nothing here touches the UI or the notification; the service does that.
 */
class NodeController(context: Context) {

    private val appContext = context.applicationContext
    private val prefs = Prefs(appContext)

    val dataDir: File = NativeBinaries.dataDir(appContext)
    val rpc = RpcClient(dataDir)

    /** Non-null only when THIS service spawned the node (vs. re-attached). */
    @Volatile
    private var process: Process? = null

    /** True when we found a node already running and simply attached to it. */
    @Volatile
    var attachedToExistingNode: Boolean = false
        private set

    /** Last N lines of bitcoind output, for diagnosing a failed start. */
    private val logTail = ArrayDeque<String>()

    /** True while the spawned process is alive (always true when attached). */
    val nodeAlive: Boolean
        get() = process?.let { it.isAlive } ?: attachedToExistingNode

    // ---------------------------------------------------------------- config

    /**
     * (Re)writes pcoin.conf. Rewritten on every start rather than only when
     * missing, so an app update that changes the seed nodes actually takes
     * effect. The datadir is app-private, so there is no user edit to clobber.
     *
     * printtoconsole=0 matters: bitcoind defaults it to ON when not daemonized,
     * which would firehose the whole debug log down the pipe we have to drain
     * for the life of the process. Logs go to <datadir>/debug.log instead;
     * genuine init errors still reach stderr and land in [logTail].
     */
    fun writeConf() {
        dataDir.mkdirs()
        val conf = buildString {
            appendLine("# Generated by PCoin Miner for Android. Rewritten on every start.")
            appendLine("server=1")
            // Must match what RpcClient dials. The miner emits 9443, which is
            // the default anyway, so this line is a no-op for every phone
            // already in the field; the wallet emits 9543 so the two apps can
            // coexist on one device.
            appendLine("rpcport=${rpc.port}")
            appendLine("listen=0")            // phones are behind CGNAT; do not advertise
            appendLine("dbcache=50")          // keep RAM for the RandomX cache
            appendLine("par=1")               // 1 script-verification thread; cores are for mining
            appendLine("maxconnections=8")
            appendLine("printtoconsole=0")
            // DEFAULT_FALLBACK_FEE is 0 in wallet.h and PCoin's mempool has no
            // fee history to estimate from, so WITHOUT this line every single
            // spend on mainnet fails with "Fee estimation failed. Fallbackfee is
            // disabled". Nothing about mining needs it, but discovering it for
            // the first time while trying to move real coins is the worst
            // possible moment.
            appendLine("fallbackfee=0.00001")
            // The seeded wallet holds only wpkh() descriptors. Taproot is active
            // from height 1 on PCoin, so a user can legitimately be given a
            // pc1p... address to pay; without this, change allocation looks for
            // a tr() descriptor, finds none, and the whole transaction fails.
            appendLine("changetype=bech32")
            // Both entries are the same machine today (seed.pc.am resolves to
            // 35.239.156.16); the literal address is a fallback for when DNS is
            // unavailable, not a second peer. A peer count of 1 on this network
            // is therefore expected, not a symptom of over-restrictive config:
            // listen=0 only stops us ADVERTISING, outbound peer discovery still
            // works and will find more peers as the network grows.
            SEED_NODES.forEach { appendLine("addnode=$it") }
        }
        File(dataDir, CONF_FILE).writeText(conf)
    }

    // ----------------------------------------------------------------- probe

    enum class Probe {
        /** Nothing on the RPC port: safe to spawn. */
        NO_NODE,

        /** Our node is up and answering. Re-attach, do not spawn. */
        OURS_READY,

        /** Our node is up but still warming up. Re-attach and wait. */
        OURS_WARMUP,

        /** Someone else's node owns the port. Never spawn a second one. */
        FOREIGN,
    }

    /**
     * Decides whether a node is already running before we consider spawning.
     *
     * This is what makes START_STICKY safe: a restarted service re-attaches to
     * the bitcoind it left behind instead of launching a second one, which on a
     * phone would mean two 256 MiB RandomX caches and two miners fighting for
     * the same cores.
     */
    fun probe(): Probe {
        val cookie = File(dataDir, RpcClient.COOKIE_FILE)
        if (!cookie.isFile) {
            // No cookie of ours has ever been written (or bitcoind removed it on
            // clean shutdown). If the port is nonetheless busy, it is not ours.
            return if (rpc.isPortOpen()) Probe.FOREIGN else Probe.NO_NODE
        }
        return try {
            rpc.call("uptime", readTimeoutMs = 5_000)
            Probe.OURS_READY
        } catch (e: RpcClient.AuthFailed) {
            Probe.FOREIGN
        } catch (e: RpcClient.NotReady) {
            // Warmup implies our cookie was accepted, so the node is ours.
            if (e.warmup) Probe.OURS_WARMUP else Probe.NO_NODE
        } catch (e: RpcClient.RpcError) {
            // It answered and authenticated; good enough.
            Probe.OURS_READY
        } catch (e: IOException) {
            Probe.NO_NODE
        }
    }

    // ----------------------------------------------------------------- spawn

    class NodeStartException(message: String) : IOException(message)

    /**
     * Execs bitcoind straight out of nativeLibraryDir.
     *
     * -datadir is mandatory on EVERY invocation: an Android app process has no
     * HOME, so bitcoind would otherwise resolve its default datadir to "/.pcoin"
     * at the filesystem root and die with "create_directories: Read-only file
     * system" before printing anything at all.
     */
    fun spawn() {
        val binary = NativeBinaries.bitcoind(appContext)
        if (!binary.isFile) {
            throw NodeStartException("libbitcoind.so missing from ${binary.parent}")
        }

        // A previous bring-up attempt may have spawned a node that came up too
        // slowly and left this method's caller retrying. Reap it before
        // spawning again, otherwise the orphan holds the datadir lock forever
        // and every future attempt fails with "Cannot obtain a lock".
        //
        // SIGTERM first, and only escalate: bitcoind flushes its chainstate on
        // SIGTERM, while a SIGKILL mid-flush is exactly what leaves a datadir
        // demanding -reindex on the next launch.
        process?.takeIf { it.isAlive }?.let { stale ->
            Log.w(TAG, "reaping stale bitcoind before respawn")
            try {
                stale.destroy() // SIGTERM
                if (!stale.waitFor(STALE_TERM_WAIT_MS, TimeUnit.MILLISECONDS)) {
                    Log.w(TAG, "stale bitcoind ignored SIGTERM; forcing")
                    stale.destroyForcibly()
                    stale.waitFor(10, TimeUnit.SECONDS)
                }
            } catch (e: InterruptedException) {
                Thread.currentThread().interrupt()
            }
        }
        process = null

        synchronized(logTail) { logTail.clear() }

        val cmd = listOf(binary.absolutePath, NativeBinaries.dataDirArg(appContext))
        Log.i(TAG, "spawning: ${cmd.joinToString(" ")}")
        val p = try {
            ProcessBuilder(cmd)
                .redirectErrorStream(true)
                .directory(dataDir)
                .apply { environment()["HOME"] = appContext.filesDir.absolutePath }
                .start()
        } catch (t: Throwable) {
            throw NodeStartException("could not exec bitcoind: ${t.javaClass.simpleName}: ${t.message}")
        }
        process = p
        attachedToExistingNode = false
        // Remember the PID. After a process death and START_STICKY restart the
        // app re-attaches to this node with no Process handle at all, and the
        // stop RPC is then the only lever it has -- which is no lever if RPC is
        // wedged. See [killPersistedNode].
        prefs.nodePid = findNodePid(binary.absolutePath)
        drain(p)
    }

    /**
     * Finds the PID of the bitcoind we just started by scanning /proc.
     *
     * java.lang.Process.pid() is not available on Android and the PID field of
     * the implementation class is a non-SDK interface, so the process table is
     * the supported way to get it. /proc only shows this app's own processes,
     * and the match is against the full executable path, so nothing else can
     * be picked up by accident.
     */
    private fun findNodePid(binaryPath: String): Int {
        val procs = File("/proc").listFiles() ?: return 0
        for (dir in procs) {
            val pid = dir.name.toIntOrNull() ?: continue
            val cmdline = try {
                File(dir, "cmdline").readText()
            } catch (e: IOException) {
                continue
            } catch (e: SecurityException) {
                continue
            }
            if (cmdline.startsWith(binaryPath)) {
                Log.i(TAG, "bitcoind pid $pid")
                return pid
            }
        }
        Log.w(TAG, "could not determine bitcoind pid")
        return 0
    }

    /**
     * Continuously reads the child's merged stdout/stderr into a bounded ring.
     *
     * Draining is not optional: an undrained pipe blocks the child as soon as
     * the OS buffer fills, which would wedge bitcoind mid-run. The ring is
     * bounded so a long mining session cannot grow the heap without limit.
     */
    private fun drain(p: Process) {
        thread(isDaemon = true, name = "pcoind-log") {
            try {
                p.inputStream.bufferedReader().forEachLine { line ->
                    Log.i(TAG_NODE, line)
                    synchronized(logTail) {
                        logTail.addLast(line)
                        while (logTail.size > LOG_TAIL_LINES) logTail.removeFirst()
                    }
                }
            } catch (e: Exception) {
                Log.d(TAG, "log drain ended: ${e.message}")
            }
        }
    }

    fun logTailText(maxLines: Int = 8): String =
        synchronized(logTail) { logTail.toList() }.takeLast(maxLines).joinToString(" | ")

    /**
     * Why the node is unhappy, in bitcoind's own words where it said anything.
     *
     * Its error lines ("Error: Cannot obtain a lock on data directory", "Please
     * restart with -reindex") are the only thing that makes a failure
     * actionable, so they take precedence over the raw log tail.
     */
    fun startupError(): String =
        lastErrorLine() ?: logTailText(3).ifBlank { "no output" }

    /** Short, user-facing reason from bitcoind's own output, if it produced one. */
    private fun lastErrorLine(): String? =
        synchronized(logTail) { logTail.toList() }
            .lastOrNull { it.contains("Error", ignoreCase = true) }
            ?.trim()
            ?.take(180)

    // ----------------------------------------------------------- rpc warmup

    /**
     * Blocks until the node serves RPC.
     *
     * @param onProgress called with the current warmup phase ("Loading block
     *   index...", "Verifying blocks...") so the UI can show real progress
     *   instead of an opaque spinner.
     */
    fun awaitRpc(timeoutMs: Long = RPC_READY_TIMEOUT_MS, onProgress: (String) -> Unit) {
        val deadline = System.currentTimeMillis() + timeoutMs
        var lastMessage = "waiting for RPC"
        while (System.currentTimeMillis() < deadline) {
            val p = process
            if (p != null && !p.isAlive) {
                val why = lastErrorLine() ?: "exit code ${p.exitValue()}"
                throw NodeStartException("bitcoind stopped during startup: $why")
            }
            try {
                rpc.call("getblockchaininfo", readTimeoutMs = 10_000)
                return
            } catch (e: RpcClient.AuthFailed) {
                throw NodeStartException(e.message ?: "RPC authentication failed")
            } catch (e: RpcClient.NotReady) {
                val msg = e.message ?: lastMessage
                if (msg != lastMessage) {
                    lastMessage = msg
                    onProgress(if (e.warmup) msg else "waiting for RPC")
                }
            } catch (e: IOException) {
                Log.d(TAG, "awaitRpc: ${e.message}")
            }
            Thread.sleep(RPC_POLL_MS)
        }
        throw NodeStartException("RPC did not come up within ${timeoutMs / 1000}s ($lastMessage)")
    }

    // ---------------------------------------------------------------- wallet

    /**
     * The wallets that are loaded right now, as the node reports them.
     *
     * A transient read, used only to decide what still needs loading. It is
     * never allowed to overwrite anything persisted.
     */
    private fun loadedWallets(): Set<String> = try {
        val arr = rpc.call("listwallets") as? JSONArray ?: return emptySet()
        (0 until arr.length()).mapNotNull { arr.optString(it).takeIf { s -> s.isNotBlank() } }.toSet()
    } catch (e: IOException) {
        emptySet()
    }

    /** Wallet directories that exist in the datadir. Empty on any RPC trouble. */
    private fun walletsOnDisk(): Set<String> = try {
        val obj = rpc.call("listwalletdir", readTimeoutMs = 30_000) as? JSONObject
        val arr = obj?.optJSONArray("wallets") ?: JSONArray()
        (0 until arr.length())
            .mapNotNull { arr.optJSONObject(it)?.optString("name") }
            .toSet()
    } catch (e: IOException) {
        Log.w(TAG, "listwalletdir failed: ${Redact.text(e.message)}")
        emptySet()
    }

    /**
     * Loads every wallet this install is known to own, and creates none.
     *
     * The whole migration story rests on this method being additive. An install
     * that predates recovery phrases has a wallet called "m" holding real,
     * spendable coins; it is loaded here and is never renamed, unloaded,
     * re-seeded or deleted. A seeded wallet, once created by setup, is loaded
     * alongside it. Both stay loaded, and the UI adds their balances up while
     * saying plainly which one has a phrase behind it.
     *
     * Nothing here calls createwallet. Wallet creation happens exactly once, in
     * the foreground, during setup or restore, where the phrase is in hand --
     * never as a side effect of a service starting up. (An earlier version of
     * this file created "m" from inside a bring-up path, which is precisely the
     * shape of bug the owner called out: an action that matters happening only
     * as a by-product of something else.)
     *
     * @return the wallet names successfully loaded.
     */
    fun loadKnownWallets(): Set<String> {
        val alreadyLoaded = loadedWallets()
        val onDisk = walletsOnDisk()
        val wanted = LinkedHashSet<String>()
        prefs.seedWalletName?.let { wanted.add(it) }
        if (prefs.hasLegacyWallet || Prefs.LEGACY_WALLET in onDisk) {
            wanted.add(Prefs.LEGACY_WALLET)
        }
        // The payout wallet is whatever the persisted record says, even if
        // neither flag above named it.
        prefs.payoutAddress?.let { wanted.add(prefs.payoutWallet) }

        val loaded = LinkedHashSet<String>()
        for (name in wanted) {
            if (name in alreadyLoaded) {
                loaded.add(name)
                continue
            }
            // Only attempt a load for something that is actually on disk, unless
            // listwalletdir itself failed (in which case try anyway rather than
            // refuse to load a wallet that may well be there).
            if (onDisk.isNotEmpty() && name !in onDisk) {
                Log.w(TAG, "wallet \"$name\" is recorded but not present in the datadir")
                continue
            }
            try {
                rpc.call("loadwallet", JSONArray().put(name), readTimeoutMs = 60_000)
                loaded.add(name)
                Log.i(TAG, "loaded wallet \"$name\"")
            } catch (e: RpcClient.RpcError) {
                if (e.code == RPC_WALLET_ALREADY_LOADED) {
                    loaded.add(name)
                } else {
                    Log.w(TAG, "could not load wallet \"$name\": ${Redact.text(e.message)}")
                }
            }
        }
        return loaded
    }

    /**
     * The payout address, read from persisted state. Never invents one.
     *
     * There is deliberately no "generate a payout address if none is stored"
     * path any more. A payout address is now only ever created by the setup or
     * restore flow, from a phrase, with the node's answer cross-checked against
     * a locally derived address. Mining without that is mining to a key nobody
     * can recover.
     */
    fun payoutAddress(): String? = prefs.payoutAddress

    /**
     * Whether the payout wallet still recognises the payout address.
     *
     * Diagnostic ONLY. It returns a verdict; it never acts on one. The persisted
     * address is authoritative and is not replaced because a check said no --
     * getaddressinfo is wallet-scoped, so with two wallets loaded a
     * confident-looking "false" is far more likely to mean "asked the wrong
     * wallet" than "the user's address is wrong". Silently replacing a payout
     * address on that evidence is how block rewards end up at a key nobody has.
     *
     * @return true if owned, false if the node clearly said no, null if the
     *   question could not be answered at all.
     */
    fun payoutAddressStillOwned(): Boolean? {
        val address = prefs.payoutAddress ?: return null
        val wallet = prefs.payoutWallet
        return try {
            val info = rpc.call(
                "getaddressinfo",
                JSONArray().put(address),
                wallet = wallet,
                readTimeoutMs = 30_000,
            ) as? JSONObject ?: return null
            info.optBoolean("ismine", false) && !info.optBoolean("iswatchonly", false)
        } catch (e: IOException) {
            // Could not ask. That is not evidence of anything.
            Log.w(TAG, "payout address check failed: ${Redact.text(e.message)}")
            null
        }
    }

    // ----------------------------------------------------------------- miner

    data class MinerInfo(
        val mining: Boolean,
        val threads: Int,
        val hashesPerSec: Double,
        val blocksFound: Long,
        val cores: Int,
    )

    fun minerInfo(): MinerInfo? = parseMinerInfo(
        try {
            rpc.call("getcpuminerinfo")
        } catch (e: IOException) {
            null
        }
    )

    private fun parseMinerInfo(raw: Any?): MinerInfo? {
        val o = raw as? JSONObject ?: return null
        return MinerInfo(
            mining = o.optBoolean("mining", false),
            threads = o.optInt("threads", 0),
            hashesPerSec = o.optDouble("hashespersec", 0.0),
            blocksFound = o.optLong("blocksfound", 0L),
            cores = o.optInt("cores", Prefs.cpuCores()),
        )
    }

    /**
     * Starts (or restarts) mining. CpuMiner::Start is documented idempotent and
     * "restarts cleanly if already running", so a thread-count change is a
     * single call with no stop/start gap.
     */
    fun startMining(address: String, threads: Int) {
        rpc.call(
            "startmining",
            JSONArray().put(address).put(threads).put(MINER_TTL_SECONDS),
            readTimeoutMs = 60_000, // first call builds the ~256 MiB RandomX cache
        )
    }

    /**
     * Asks the node to stop hashing. Never throws.
     *
     * Deliberately safe to call at any time, including when no node is running:
     * CpuMiner::Stop early-returns when idle, so the caller does not have to
     * know whether the miner is up. Every gate transition and every error path
     * calls it for exactly that reason.
     */
    fun stopMining(timeoutMs: Int = 30_000) {
        try {
            rpc.call("stopmining", readTimeoutMs = timeoutMs)
        } catch (e: IOException) {
            Log.w(TAG, "stopmining failed: ${e.message}")
        }
    }

    // ----------------------------------------------------------------- stats

    /** getbalances.mine for one wallet. -1 means "not known". */
    data class Balances(
        val confirmed: Double = -1.0,
        val immature: Double = -1.0,
        val pending: Double = -1.0,
        /**
         * Money in a transaction the wallet knows about that getbalances counts
         * in NO category at all. -1 when there is none or it was not looked for.
         *
         * Core's IsTrusted requires an unconfirmed transaction to be in the
         * mempool. After an unclean node restart -- force-stop, app update,
         * reboot, OOM kill -- the mempool is empty, so an in-flight transaction
         * is neither trusted nor untrusted_pending and every getbalances figure
         * reads 0.00 while the wallet genuinely holds the coins. Observed for
         * about one block on pcoin-hd: trusted 0, untrusted_pending 0,
         * immature 0, with listtransactions still showing the transaction at
         * confirmations 0. A bare 0.00 in that state reads as "my money is
         * gone", so it is sourced from listtransactions instead and labelled.
         */
        val inFlight: Double = -1.0,
        val inFlightCount: Int = 0,
        /**
         * Depth of the closest-to-mature coinbase, or -1 for unknown.
         *
         * -1 covers three different situations that all mean the same thing to
         * a caller: nothing is maturing, the node could not be asked, or it was
         * not looked for. None of them licenses printing a number.
         */
        val bestImmatureConfirmations: Long = -1L,
    ) {
        val known: Boolean get() = confirmed >= 0 || immature >= 0

        operator fun plus(other: Balances): Balances {
            if (!known) return other
            if (!other.known) return this
            fun add(a: Double, b: Double) = maxOf(a, 0.0) + maxOf(b, 0.0)
            val flight = when {
                inFlight < 0 && other.inFlight < 0 -> -1.0
                else -> add(inFlight, other.inFlight)
            }
            return Balances(
                add(confirmed, other.confirmed),
                add(immature, other.immature),
                add(pending, other.pending),
                flight,
                inFlightCount + other.inFlightCount,
                // The DEEPEST of the two, because the question is "when does
                // something become spendable" and the answer is whichever coin
                // matures first. maxOf works on -1 too: an unknown side simply
                // loses to a known one, and two unknowns stay unknown.
                maxOf(bestImmatureConfirmations, other.bestImmatureConfirmations),
            )
        }
    }

    data class Stats(
        val height: Long,
        val headers: Long,
        val verificationProgress: Double,
        val initialBlockDownload: Boolean,
        val peers: Int,
        /**
         * The tip block's own timestamp, in seconds. 0 when not known.
         *
         * `time`, deliberately, not `mediantime`: mediantime lags 5 blocks by
         * construction, which at PCoin's measured ~868 s spacing is over an
         * hour, and any freshness check built on it would be meaningless.
         */
        val tipTimeSec: Long,
        /** Balance of the wallet the recovery phrase recreates, if there is one. */
        val seedBalance: Balances?,
        /** Balance of the pre-phrase wallet, if this install has one. */
        val legacyBalance: Balances?,
        val miner: MinerInfo?,
    ) {
        val totalBalance: Balances
            get() = (seedBalance ?: Balances()) + (legacyBalance ?: Balances())
    }

    /**
     * One round trip for the chain and miner numbers, then one getbalances per
     * loaded wallet.
     *
     * The balances are fetched per wallet rather than batched with the rest
     * because they are wallet-scoped and this install can legitimately have two
     * wallets: the seeded one and the pre-phrase one. Adding them up without
     * saying which is which would hide the only thing the user needs to know --
     * how much of their money the twelve words actually recover.
     */
    fun stats(loadedWallets: Set<String>): Stats {
        val r = rpc.batch(
            listOf("getblockchaininfo", "getconnectioncount", "getcpuminerinfo"),
            readTimeoutMs = STATS_TIMEOUT_MS,
        )

        val chain = r["getblockchaininfo"] as? JSONObject

        val seedWallet = prefs.seedWalletName
        val seedBalance = seedWallet?.takeIf { it in loadedWallets }?.let { balances(it) }
        val legacyBalance = Prefs.LEGACY_WALLET
            .takeIf { it != seedWallet && it in loadedWallets }
            ?.let { balances(it) }

        return Stats(
            height = chain?.optLong("blocks", -1L) ?: -1L,
            headers = chain?.optLong("headers", -1L) ?: -1L,
            verificationProgress = chain?.optDouble("verificationprogress", -1.0) ?: -1.0,
            // Absent chain info counts as "still syncing": the gate must fail
            // closed, not start hashing on an unknown tip.
            initialBlockDownload = chain?.optBoolean("initialblockdownload", true) ?: true,
            peers = (r["getconnectioncount"] as? Number)?.toInt() ?: -1,
            tipTimeSec = chain?.optLong("time", 0L) ?: 0L,
            seedBalance = seedBalance,
            legacyBalance = legacyBalance,
            miner = parseMinerInfo(r["getcpuminerinfo"]),
        )
    }

    private fun balances(wallet: String): Balances? = try {
        val mine = (rpc.call("getbalances", wallet = wallet, readTimeoutMs = STATS_TIMEOUT_MS)
            as? JSONObject)?.optJSONObject("mine")
        if (mine == null) null else {
            val confirmed = mine.optDouble("trusted", -1.0)
            val immature = mine.optDouble("immature", -1.0)
            val pending = mine.optDouble("untrusted_pending", -1.0)
            val flight =
                if (confirmed == 0.0 && immature == 0.0 && pending == 0.0) inFlight(wallet)
                else null
            Balances(
                confirmed = confirmed,
                immature = immature,
                pending = pending,
                inFlight = flight?.first ?: -1.0,
                inFlightCount = flight?.second ?: 0,
                // Only asked when there is actually something maturing, so the
                // normal case costs no extra round trip.
                bestImmatureConfirmations = if (immature > 0.0) bestImmature(wallet) else -1L,
            )
        }
    } catch (e: IOException) {
        // Unknown, not zero. Showing 0.00 for a wallet whose balance simply
        // could not be read would look exactly like the money being gone.
        null
    }

    /**
     * Depth of the most-confirmed coinbase that is still immature.
     *
     * Answers "how many more blocks until SOMETHING becomes spendable", which is
     * the question a person actually has when they see a maturing balance. The
     * screen used to render a hardcoded 100 into a string that promises a
     * remaining count, so it never moved.
     *
     * @return confirmations of the closest-to-mature coinbase, or -1 when the
     *   node could not be asked or nothing is maturing. -1 is unknown, never
     *   zero: a caller must render "not spendable yet" without a number rather
     *   than claim the coins are one block away.
     */
    private fun bestImmature(wallet: String): Long = try {
        val list = rpc.call(
            "listtransactions",
            JSONArray().put("*").put(IN_FLIGHT_SCAN).put(0).put(true),
            wallet = wallet,
            readTimeoutMs = STATS_TIMEOUT_MS,
        ) as? JSONArray
        var best = -1L
        for (i in 0 until (list?.length() ?: 0)) {
            val tx = list?.optJSONObject(i) ?: continue
            if (tx.optString("category") != "immature") continue
            // -1 default is deliberate: a missing confirmations field must not
            // read as a coinbase sitting at depth 0.
            val c = tx.optLong("confirmations", -1L)
            if (c in 0 until COINBASE_SPENDABLE_DEPTH && c > best) best = c
        }
        best
    } catch (e: IOException) {
        -1L
    }

    /**
     * What a wallet holds that getbalances reported in no category at all.
     *
     * Only asked when every getbalances figure is exactly zero, so this costs
     * nothing in the normal case. getwalletinfo.txcount is checked first
     * precisely so a genuinely empty wallet -- the overwhelmingly common
     * all-zero case -- goes no further and is still shown as a plain 0.00.
     *
     * @return incoming value and transaction count, or null when there is
     *   nothing in flight or the node could not be asked. Only POSITIVE amounts
     *   are summed: for a self-send, netting the send leg against the receive
     *   leg would report roughly minus-the-fee, when what the user needs to see
     *   is the value on its way back to them.
     */
    private fun inFlight(wallet: String): Pair<Double, Int>? = try {
        val txCount = (rpc.call("getwalletinfo", wallet = wallet, readTimeoutMs = STATS_TIMEOUT_MS)
            as? JSONObject)?.optInt("txcount", 0) ?: 0
        if (txCount <= 0) null else {
            val list = rpc.call(
                "listtransactions",
                JSONArray().put("*").put(IN_FLIGHT_SCAN).put(0).put(true),
                wallet = wallet,
                readTimeoutMs = STATS_TIMEOUT_MS,
            ) as? JSONArray
            var total = 0.0
            var count = 0
            for (i in 0 until (list?.length() ?: 0)) {
                val tx = list?.optJSONObject(i) ?: continue
                if (tx.optInt("confirmations", 1) > 0) continue
                if (tx.optBoolean("abandoned", false)) continue
                val amount = tx.optDouble("amount", 0.0)
                if (amount > 0) total += amount
                count++
            }
            if (count == 0) null else total to count
        }
    } catch (e: IOException) {
        null
    }

    // -------------------------------------------------------------- shutdown

    /**
     * Stops mining, asks the node to shut down cleanly, and only force-kills as
     * a last resort. A clean stop matters: bitcoind flushes the chainstate on
     * shutdown, and a SIGKILL mid-flush costs a long reindex next launch.
     */
    fun shutdown() {
        // Short timeouts here on purpose: onDestroy joins this thread for only
        // a few seconds, and of the two calls the one that MUST get through is
        // stopmining -- a node left running is a nuisance, a node left hashing
        // is a hot phone with no notification.
        stopMining(SHUTDOWN_RPC_TIMEOUT_MS)
        try {
            rpc.call("stop", readTimeoutMs = SHUTDOWN_RPC_TIMEOUT_MS)
        } catch (e: IOException) {
            Log.w(TAG, "stop RPC failed: ${e.message}")
        }

        val p = process
        if (p == null) {
            // We attached to a node we did not spawn, so there is no Process to
            // wait on or destroy. If the stop RPC did not take, the persisted
            // PID is the only remaining way to stop it.
            waitForPortClosed(ATTACHED_STOP_WAIT_MS)
            if (rpc.isPortOpen(400)) killPersistedNode()
            attachedToExistingNode = false
            return
        }
        try {
            if (!p.waitFor(SHUTDOWN_WAIT_MS, TimeUnit.MILLISECONDS)) {
                Log.w(TAG, "bitcoind did not exit in ${SHUTDOWN_WAIT_MS / 1000}s; forcing")
                p.destroyForcibly()
                p.waitFor(5, TimeUnit.SECONDS)
            }
        } catch (e: InterruptedException) {
            p.destroyForcibly()
            Thread.currentThread().interrupt()
        }
        process = null
        prefs.nodePid = 0
    }

    /**
     * Last resort for a node this process did not spawn: signal the PID we
     * recorded when it WAS spawned.
     *
     * PIDs are recycled, so the identity of the process is verified against
     * /proc/<pid>/cmdline before anything is sent -- signalling a stranger
     * because a number was reused would be far worse than leaving a node up.
     * SIGTERM first so bitcoind still gets to flush its chainstate.
     */
    private fun killPersistedNode() {
        val pid = prefs.nodePid
        if (pid <= 0) {
            Log.w(TAG, "node still up but no PID recorded; cannot stop it")
            return
        }
        val cmdline = try {
            File("/proc/$pid/cmdline").readText()
        } catch (e: IOException) {
            ""
        }
        // Match the FULL path, not the basename.
        //
        // The basename is identical in every PCoin app, and PIDs are recycled.
        // Once the miner and the wallet are both installed, a stale pid from one
        // can name the other's live bitcoind -- and this code would then SIGTERM
        // it, potentially mid-chainstate-flush, on a node holding a wallet.
        // The full path contains the applicationId, so it cannot cross apps.
        val ourBinary = NativeBinaries.bitcoind(appContext).absolutePath
        if (!cmdline.contains(ourBinary)) {
            Log.w(TAG, "pid $pid is not our bitcoind (\"${cmdline.take(60)}\"); not signalling")
            prefs.nodePid = 0
            return
        }
        Log.w(TAG, "stop RPC did not take; sending SIGTERM to bitcoind pid $pid")
        android.os.Process.sendSignal(pid, SIGTERM)
        waitForPortClosed(ATTACHED_STOP_WAIT_MS)
        if (rpc.isPortOpen(400) && File("/proc/$pid/cmdline").exists()) {
            Log.w(TAG, "bitcoind pid $pid ignored SIGTERM; killing")
            android.os.Process.killProcess(pid)
        }
        prefs.nodePid = 0
    }

    private fun waitForPortClosed(timeoutMs: Long) {
        val deadline = System.currentTimeMillis() + timeoutMs
        while (System.currentTimeMillis() < deadline) {
            if (!rpc.isPortOpen(400)) return
            try {
                Thread.sleep(500)
            } catch (e: InterruptedException) {
                Thread.currentThread().interrupt()
                return
            }
        }
    }

    /**
     * Records that a node was found already running.
     *
     * Deliberately does NOT discard a live [process] handle: a bring-up retry
     * can reach this method for a node THIS controller spawned a moment ago,
     * and throwing the handle away would forfeit our only way to force-kill it.
     */
    fun markAttached() {
        if (process?.isAlive != true) process = null
        attachedToExistingNode = true
    }

    companion object {
        const val TAG = "PCoinNode"
        const val TAG_NODE = "pcoind"

        const val CONF_FILE = "pcoin.conf"

        /**
         * Dead-man's switch handed to the node, in seconds.
         *
         * Every battery and thermal limit is enforced by this service. If the
         * service dies -- killed by the OS, crashed, or replaced during an app
         * update -- the node it spawned keeps hashing with nothing left to stop
         * it, and the phone cooks. That happened during testing.
         *
         * The node stops mining on its own unless it hears from us within this
         * window. The 3 s stats poll is the check-in, so 45 s leaves ~15 ticks
         * of slack for a slow RPC while still capping how long an abandoned
         * miner can run.
         */
        const val MINER_TTL_SECONDS = 45

        /** RPC_WALLET_ALREADY_LOADED in rpc/protocol.h. */
        private const val RPC_WALLET_ALREADY_LOADED = -35

        private val SEED_NODES = listOf("seed.pc.am:9444", "35.239.156.16:9444")

        /** As it appears in /proc/<pid>/cmdline; used to identify our child. */
        private const val BITCOIND_SO_NAME = "libbitcoind.so"
        private const val SIGTERM = 15

        private const val LOG_TAIL_LINES = 200
        private const val RPC_POLL_MS = 1_000L
        private const val RPC_READY_TIMEOUT_MS = 300_000L   // block index load can be slow on flash
        private const val SHUTDOWN_WAIT_MS = 60_000L        // chainstate flush
        private const val SHUTDOWN_RPC_TIMEOUT_MS = 5_000   // onDestroy joins for 8 s
        private const val ATTACHED_STOP_WAIT_MS = 30_000L
        private const val STALE_TERM_WAIT_MS = 10_000L
        private const val STATS_TIMEOUT_MS = 10_000

        /**
         * How far back to look for an unconfirmed transaction that getbalances
         * counted nowhere. Only ever reached when every balance is zero, so a
         * generous window costs nothing in the normal case.
         */
        private const val IN_FLIGHT_SCAN = 50

        /** Depth at which a coinbase becomes spendable. Consensus, not a guess. */
        private const val COINBASE_SPENDABLE_DEPTH = 101L
    }
}
