; PCoin for Windows - installer
;
; Bundles the node, the CLI and the tray app so a user gets a working install
; from one double-click, with no PowerShell and no separate download step.
;
; Build:
;   "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" /DMyVersion=1.2.2 installer.iss
;
; Expects, relative to this file:
;   payload\bitcoind.exe       from the published pcoin-<ver>-win64.zip
;   payload\bitcoin-cli.exe    same
;   PCoinTray.exe              built by build.bat
;
; Deliberately NOT mining on install. A node that mines before it has synced
; builds on a chain it has not verified, and the tray defaults to 0 threads for
; exactly that reason. The user turns it on when they are ready.

#ifndef MyVersion
  #define MyVersion "1.2.2"
#endif

#define MyAppName "PCoin"
#define MyPublisher "PCoin Project"
#define MyURL "https://pc.am"

[Setup]
AppId={{8E2C1A74-3F5B-4A1E-9C6D-PC01N0DE2026}
AppName={#MyAppName}
AppVersion={#MyVersion}
AppVerName={#MyAppName} {#MyVersion}
AppPublisher={#MyPublisher}
AppPublisherURL={#MyURL}
AppSupportURL=https://github.com/pars5555/pcoin
DefaultDirName=C:\PCoin
DisableDirPage=no
DefaultGroupName={#MyAppName}
OutputBaseFilename=pcoin-{#MyVersion}-win64-setup
OutputDir=dist
Compression=lzma2/max
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
WizardStyle=modern
UninstallDisplayName={#MyAppName} {#MyVersion}
LicenseFile=..\..\COPYING

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "startupicon"; Description: "Start PCoin automatically when I sign in"; GroupDescription: "Startup:"
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Shortcuts:"; Flags: unchecked

[Files]
Source: "payload\bitcoind.exe";    DestDir: "{app}"; Flags: ignoreversion
Source: "payload\bitcoin-cli.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "PCoinTray.exe";           DestDir: "{app}"; Flags: ignoreversion
Source: "README.md";               DestDir: "{app}"; DestName: "README.txt"; Flags: ignoreversion isreadme

[Dirs]
; The datadir lives under the install directory so an uninstall can leave it
; alone deliberately (see [UninstallDelete] - the wallet is NOT removed).
Name: "{app}\data"

[Code]
// The config file is pcoin.conf, NOT bitcoin.conf. Getting this wrong gives a
// node that silently ignores every setting, which is the single most common
// mistake newcomers make with this fork.
procedure WriteConfIfAbsent;
var
  ConfPath: String;
  Lines: TArrayOfString;
begin
  ConfPath := ExpandConstant('{app}\data\pcoin.conf');
  if FileExists(ConfPath) then
    Exit;
  SetArrayLength(Lines, 12);
  Lines[0]  := '# Generated by the PCoin installer. Safe to edit.';
  Lines[1]  := 'server=1';
  Lines[2]  := 'listen=1';
  Lines[3]  := 'dbcache=300';
  Lines[4]  := 'maxconnections=40';
  Lines[5]  := '# Fee estimation has no history on a chain this young, so a';
  Lines[6]  := '# fallback is required or every send fails.';
  Lines[7]  := 'fallbackfee=0.00001';
  Lines[8]  := 'changetype=bech32';
  Lines[9]  := 'addnode=35.239.156.16:9444';
  Lines[10] := 'addnode=35.238.47.14:9444';
  Lines[11] := 'addnode=178.105.3.51:9444';
  SaveStringsToFile(ConfPath, Lines, False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    WriteConfIfAbsent;
end;

[Icons]
Name: "{group}\PCoin";              Filename: "{app}\PCoinTray.exe"
Name: "{group}\PCoin data folder";  Filename: "{app}\data"
Name: "{group}\Uninstall PCoin";    Filename: "{uninstallexe}"
Name: "{userdesktop}\PCoin";        Filename: "{app}\PCoinTray.exe"; Tasks: desktopicon
Name: "{userstartup}\PCoin";        Filename: "{app}\PCoinTray.exe"; Tasks: startupicon

[Run]
Filename: "{app}\PCoinTray.exe"; Description: "Start PCoin now"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Stop the node before the files go, so the chainstate is flushed rather than
; left needing a reindex.
Filename: "{app}\bitcoin-cli.exe"; Parameters: "-datadir=""{app}\data"" stop"; Flags: runhidden; RunOnceId: "StopNode"

[UninstallDelete]
Type: files; Name: "{app}\pcoin-selftest.txt"

[Messages]
; The wallet lives in {app}\data. Uninstalling must never take it, and the user
; is told plainly where it is rather than left to guess.
ConfirmUninstall=Remove %1?%n%nYour wallet and the blockchain in the data folder will be LEFT IN PLACE. If you want them gone, delete the folder yourself afterwards.
