#!/usr/bin/env python3
"""Give every pc.am page a canonical URL and a shared-link preview.

    python contrib/deploy/make-share-tags.py            # add what is missing
    python contrib/deploy/make-share-tags.py --check     # list pages without them

WHY
A link to pc.am posted in Telegram, X or Discord showed no title, no
description and no image -- a bare URL, which reads as a dead link. The project
announces through Telegram, so every announcement was carrying the weakest
possible preview. Adding og:* to the homepage alone is not enough: the links
people actually paste are /mining/ and /wallet/.

WHAT IT TAKES FROM THE PAGE AND WHAT IT REFUSES TO INVENT
og:title is the page's own <title>; og:description is its own meta description.
A page with no description gets NO og:description rather than a sentence this
script made up -- a preview that is merely sparse is better than one that
describes the page wrongly, and inventing copy is how a public page ends up
promising something nobody decided (CLAUDE.md 8b).

og:image is one STATIC card for the whole site, with no figures on it. A card
per page would be better and a card with numbers on it would be worse: a
picture circulates for months and a number baked into it cannot be corrected.

THE LINE-ENDING TRAP
site/index.html is CRLF in the working tree and LF in the committed blob, and
the rest of site/ is LF in both. A text-mode round trip rewrites every line in
the file, which turns a 30-line insertion into a whole-file diff and silently
breaks every anchored edit made afterwards. So this reads BYTES, detects the
file's own ending, and writes BYTES.
"""
import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "site"
BASE = "https://pc.am"
IMAGE = f"{BASE}/img/og-pc-am.png"
IMAGE_ALT = "PCoin — the coin anyone can mine. An independent Layer-1 blockchain."

# Same rule as make-sitemap.py: a path segment of 16+ hex characters is the
# unlisted admin path, not a page. It gets no tags and no canonical, because a
# canonical URL is a request to index it.
SECRET = re.compile(r"^[0-9a-f]{16,}$", re.I)

TITLE = re.compile(rb"<title>(.*?)</title>", re.S | re.I)
DESC = re.compile(rb'<meta\s+name="description"\s+content="(.*?)"\s*/?>', re.S | re.I)
HAS_OG = re.compile(rb'property="og:title"', re.I)
HAS_CANON = re.compile(rb'rel="canonical"', re.I)


def url_for(rel):
    if rel.name == "index.html":
        d = rel.parent.as_posix()
        return "/" if d == "." else f"/{d}/"
    return "/" + rel.as_posix()


def attr(s):
    """Escape for an HTML attribute. The titles carry & and -- already
    entity-encoded in some pages and raw in others, so unescape first and
    re-escape once: double-encoding turns &amp; into &amp;amp; in the preview."""
    return html.escape(html.unescape(s), quote=True)


def tags_for(url, title, desc, want_canonical):
    out = [
        "",
        "<!-- Shared-link preview and canonical URL. Generated by",
        "     contrib/deploy/make-share-tags.py -- rerun it after adding a page. -->",
    ]
    # TWO CANONICALS ARE WORSE THAN NONE: a search engine faced with a pair it
    # cannot reconcile may discard both, so a page that already declares one
    # keeps it rather than gaining a rival. site/download/index.html had one
    # and would have been given a second by the first version of this.
    if want_canonical:
        out.append(f'<link rel="canonical" href="{BASE}{url}">')
    out += [
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="PCoin">',
        f'<meta property="og:url" content="{BASE}{url}">',
        f'<meta property="og:title" content="{attr(title)}">',
    ]
    if desc:
        out.append(f'<meta property="og:description" content="{attr(desc)}">')
    out += [
        f'<meta property="og:image" content="{IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{attr(IMAGE_ALT)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:site" content="@PCoinPCN">',
        f'<meta name="twitter:title" content="{attr(title)}">',
    ]
    if desc:
        out.append(f'<meta name="twitter:description" content="{attr(desc)}">')
    out.append(f'<meta name="twitter:image" content="{IMAGE}">')
    return out


def process(path, apply):
    raw = path.read_bytes()
    rel = path.relative_to(SITE)
    has_canon = bool(HAS_CANON.search(raw))
    if HAS_OG.search(raw) and has_canon:
        return "already has them", False

    mt = TITLE.search(raw)
    if not mt:
        # No title means no honest og:title, and og:title is required for a
        # preview to render at all. Report it rather than guessing one.
        return "NO <title> -- skipped, add one first", False
    title = mt.group(1).decode("utf-8", "replace").strip()
    md = DESC.search(raw)
    desc = md.group(1).decode("utf-8", "replace").strip() if md else ""

    eol = b"\r\n" if b"\r\n" in raw[:4000] else b"\n"
    anchor = md.group(0) if md else mt.group(0)
    if raw.count(anchor) != 1:
        return f"anchor appears {raw.count(anchor)} times -- skipped", False

    lines = tags_for(url_for(rel), title, desc, not has_canon)
    ins = eol.join(s.encode("utf-8") for s in lines)
    if apply:
        path.write_bytes(raw.replace(anchor, anchor + ins, 1))
    return ("%s, %s description, %s canonical, %s" % (
        "CRLF" if eol == b"\r\n" else "LF",
        "with" if desc else "NO",
        "new" if not has_canon else "keeps its own",
        "added" if apply else "would add"), True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report pages missing the tags; exit 1 if any are")
    a = ap.parse_args()

    missing = 0
    for f in sorted(SITE.rglob("*.html")):
        rel = f.relative_to(SITE)
        if any(SECRET.match(p) for p in rel.parts):
            continue
        note, changed = process(f, apply=not a.check)
        if changed:
            missing += 1
        print(f"{rel.as_posix():<34} {note}")

    if a.check and missing:
        print(f"\n{missing} page(s) have no share preview. Run without --check.",
              file=sys.stderr)
        return 1
    print(f"\n{missing} page(s) {'need tags' if a.check else 'updated'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
